### ISSUE TITLE
Qsoas fails to build on MacOS 10.15 and 11 with newest Xcode

### ISSUE THREAD

**Issue by iMichka** [fourmond/QSoas#2]
Hi. I am a Homebrew maintainer. Homebrew is package manager for macOS and Linux.
We noticed that QSoas 3.0 does not build with the newest Xcode versions anymore.

The linker step is asking for `-mmacosx-version-min=10.13`:
> 2022-01-20T13:32:59.4363210Z /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -L/usr/local/opt/mruby/lib -L/usr/local/opt/gsl/lib -headerpad_max_install_names  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -o QSoas.app/Contents/MacOS/QSoas

I see a bunch of warnings:
> 2022-01-20T13:32:59.4378760Z ld: warning: dylib (/usr/local/opt/gsl/lib/libgsl.dylib) was built for newer macOS version (10.15) than being linked (10.13)
2022-01-20T13:32:59.4379880Z ld: warning: dylib (/usr/local/opt/gsl/lib/libgslcblas.dylib) was built for newer macOS version (10.15) than being linked (10.13)
2022-01-20T13:32:59.4380990Z ld: warning: object file (/usr/local/opt/mruby/lib/libmruby.a(array.o)) was built for newer macOS version (10.15) than being linked (10.13)
2022-01-20T13:32:59.4382120Z ld: warning: object file (/usr/local/opt/mruby/lib/libmruby.a(object.o)) was built for newer macOS version (10.15) than being linked (10.13)
2022-01-20T13:32:59.4383260Z ld: warning: object file (/usr/local/opt/mruby/lib/libmruby.a(state.o)) was built for newer macOS version (10.15) than being linked (10.13)
2022-01-20T13:32:59.4384570Z ld: warning: object file (/usr/local/opt/mruby/lib/libmruby.a(etc.o)) was built for newer macOS version (10.15) than being linked (10.13)
2022-01-20T13:32:59.4385700Z ld: warning: object file (/usr/local/opt/mruby/lib/libmruby.a(class.o)) was built for newer macOS version (10.15) than being linked (10.13)
2022-01-20T13:32:59.4386830Z ld: warning: object file (/usr/local/opt/mruby/lib/libmruby.a(variable.o)) was built for newer macOS version (10.15) than being linked (10.13)

And here is the error:
> Undefined symbols for architecture x86_64:
  "MRuby::detectParameters(QByteArray const&)", referenced from:
      Expression::variablesNeeded(QString const&, QStringList const&) in expression.o
      mRubyArgs(QString const&, QString, QHash<QString, ArgumentMarshaller*> const&) in mruby.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [QSoas.app/Contents/MacOS/QSoas] Error 1

I tried setting the QMAKE_MACOSX_DEPLOYMENT_TARGET to 10.15 in the QSoas.pro file, but hit another bunch of errors.
Any help is welcome.
Here is the issue on our side for reference: https://github.com/Homebrew/homebrew-core/pull/90495

**Comment by fourmond** [comment]
As far as I can tell, this comes from the fact that you are probably building with mruby 3. I have personally not had the time to try that yet, so I don't know if it works. If you have means to switch back to mruby 2 for the time being, I guess this is the best strategy. If not, change all the instances of `MRUBY_RELEASE_MAJOR == 2` into `MRUBY_RELEASE_MAJOR >= 2` in `src/mruby.cc`. I can change that if you want, although, honestly, I can't guarantee that QSoas will work with mruby 3 as of now (and unless it works out of the box, it is a lot of work from me).

The warnings about the macos version are not at the origin of this. They indicate that you have heterogeneous build machines. I'm unsure whether this will cause trouble or not.

**Comment by iMichka** [comment]
I confirm that it does build with `mruby 2`. I don't know how we were able to build it with version 3. Maybe our CI missed that. Anyway, I am reverting to `mruby 2` to be on the safe side, which leaves you some time to migrate to the new version.
If https://github.com/Homebrew/homebrew-core/pull/93798 is passes and is accepted on our side, we should be fine for some time. But moving to updated versions like newest qt / mruby might be needed in the long run.

**Comment by fourmond** [comment]
OK, I'm relieved it appears to work. I know I need to upgrade, but upgrading just one dependency on three distinct platforms is a nightmare that takes anything from half a day to a full week, so I tend to do that only when forced to... Qt6 should be fine, but mruby tends to be more delicate as a dependency. The gsl library is generally no issue.

**Comment by iMichka** [comment]
Thanks. I know how hard it can be, good luck to you. I bought you some time on our side, so this issue can be closed now.
